serial_number: "UNKNOWN"
reset_timestamps_delay: -1.0
imu_calibration_sample_size: 1000

imu_bias:
  ax: 0.0
  ay: 0.0
  az: 0.0
  wx: 0.0
  wy: 0.0
  wz: 0.0

# DAVIS346 Specific Parameters - From ROS Driver example - may need changed
aps_enabled: true
dvs_enabled: true
imu_enabled: true

imu_acc_scale: 3
imu_gyro_scale: 3

exposure: 4000
frame_delay: 0
max_events: 0
streaming_rate: 30

ADC_RefHigh_volt: 24
ADC_RefHigh_curr: 7
ADC_RefLow_volt: 1
ADC_RefLow_curr: 7

DiffBn_coarse: 4
DiffBn_fine: 39

OFFBn_coarse: 4
OFFBn_fine: 0

ONBn_coarse: 6
ONBn_fine: 255

PrBp_coarse: 2
PrBp_fine: 255

PrSFBp_coarse: 1
PrSFBp_fine: 199

RefrBp_coarse: 3
RefrBp_fine: 7

# DAVIS346 Params Set in Code - Not sure where specified - andrews attempt to keep everything off below
frame_mode: 0
frame_interval: 0
mu_low_pass_filter: 3  # ON (Choose between 1-6)
imu_sample_rate_divider: 0  # Keep at 0 when LPF is enabled

# Hardware Filtering (DVS) - Default OFF
pixel_auto_train: false
pixel_0_row: 0
pixel_0_column: 0
pixel_1_row: 0
pixel_1_column: 0
pixel_2_row: 0
pixel_2_column: 0
pixel_3_row: 0
pixel_3_column: 0
pixel_4_row: 0
pixel_4_column: 0
pixel_5_row: 0
pixel_5_column: 0
pixel_6_row: 0
pixel_6_column: 0
pixel_7_row: 0
pixel_7_column: 0

# Background Activity Filter (Default OFF)
background_activity_filter_enabled: false
background_activity_filter_time: 0

# Refractory Period Filter (Default OFF)
refractory_period_enabled: false
refractory_period_time: 0

# ROI Filter (Defaults to full frame)
roi_start_column: 0
roi_start_row: 0
roi_end_column: 0
roi_end_row: 0

# Skip Events Filter (Default OFF)
skip_enabled: false
skip_every: 1

# Polarity Filter (Default OFF)
polarity_flatten: false
polarity_suppress: false
polarity_suppress_type: 0

# APS Region of Interest (Default: Disabled)
aps_roi_start_column: 0
aps_roi_start_row: 0
aps_roi_end_column: 0
aps_roi_end_row: 0